unique_ids:
  assets:
    theme.css: A2Y5M3X5RBU4JFSFIRU7NFJG264JXM63
  forms:
    Form1: 5BUBJHESCXTENLWFAJ7TAVH3N7UIUBTR
    Layouts.BaseLayout: PKYE26KMMY5DASM4RPP3DPRA7YJ6RS7J
  modules:
    Layouts: NKF6DTYMFZUBZLPVJ7K4MLMWVAKPCPTV
  scripts: {}
  server_modules: {}
