import anvil.server

# This is a server module. It runs on the Anvil server,
# rather than in the user's browser.
#
# To allow anvil.server.call() to call functions here, we mark
# them with @anvil.server.callable.
# Here is an example - you can replace it with your own:
#
# @anvil.server.callable
# def say_hello(name):
#   print("Hello, " + name + "!")
#   return 42
#
import sys, os, re
import anvil.server  # Ključno za Anvil

EXACT = [
  
  ('razboleo', 'razbolio'),
  ('sledeći', 'slijedeći'), 
  ('zamenik', 'zamjenik'),
  ('svideo', 'svidio'),
  ('uvideo', 'uvidio'),
  ('napred', 'naprijed'),
  ('pevac', 'kokot'),
  ('video', 'vidio'),
  ('vreme', 'vrijeme'),
  ('doneo', 'donijeo'),
  ('sreda', 'srijeda'),
  ('hteo', 'htio'),
  ('uspeo', 'uspio'),
  ('uvid', 'uvid'),
  ('dete', 'dijete'),
  ('plen', 'plijen'),
  ('žele', 'žele'),
  ('sme', 'smije'),
  ('smeo', 'smio'),
  ('dele', 'dijele'),
  ('dece', 'djece'),
  ('leta', 'ljeta'),
  ('dve', 'dvije'),
  ('pre', 'prije'),
  ('bes', 'bijes'),
  ('deo', 'dio'),
  ('dev', 'djev'),
  ('lek', 'lijek'),



]


STEMS = [
    ('četvoromeseč', 'četvoromjeseč'),
    ('devetomeseč', 'devetomjeseč'),
    ('desetomeseč', 'desetomjeseč'),
    ('pretpostavk', 'pretpostavk'),
    ('predstavnik', 'predstavnik'),
    ('jednomeseč', 'jednomjeseč'),
    ('petomeseč', 'petomjeseč'),
    ('šestomeseč', 'šestomjeseč'),
    ('sedmomeseč', 'sedmmjeseč'),
    ('osmomeseč', 'osmoomjeseč'),
    ('presecanj', 'presijecanj'),
    ('predvide', 'predvidje'),
    ('potpreds', 'potpredsj'),
    ('dragocen', 'dragocjen'),
    ('dvomeseč', 'dvomjeseč'),
    ('tromeseč', 'tromjeseč'),
    ('opredeli', 'opredijeli'),
    ('ponedelj', 'ponedjelj'),
    ('opredelj', 'opredjelj'),
    ('pregreja', 'pregrija'),
    ('povredi', 'povrijedi'),
    ('obavest', 'obavijest'),
    ('izbegav', 'izbjegav'),
    ('delegat', 'delegat'),
    ('osvedoč', 'osvjedoč'),
    ('poverlj', 'povjerlj'),
    ('obavešt', 'obavješt'),
    ('zabelež', 'zabiljež'),
    ('podsmeh', 'podsmjeh'),
    ('prebole', 'prebolje'),
    ('premešt', 'premješt'),
    ('premest', 'premjest'),
    ('odeljak', 'odjeljak'),
    ('doprine', 'doprinije'),
    ('neizbež', 'neizbjež'),
    ('neizmer', 'neizmjer'),
    ('letelic', 'letjelic'),
    ('nadžive', 'nadživje'),
    ('prosleđ', 'prosljeđ'),
    ('osvetli', 'osvijetli'),
    ('osvetlj', 'osvjetlj'),
    ('pobeg', 'pobjeg'),
    ('pobegl', 'pobjegl'),
    ('prevar', 'prevar'),
    ('povest', 'povijest'),
    ('prosle', 'proslije'),
    ('gnezdo', 'gnijezdo'),
    ('unapre', 'unaprije'),
    ('razbole', 'razbolje'),
    ('zaplena', 'zapljena'),
    ('zaplenu', 'zapljenu'),
    ('zapleni', 'zaplijeni'),
    ('zaplene', 'zapljene'),
    ('proceni', 'procijeni'),
    ('procena', 'procjena'),
    ('procene', 'procjene'),
    ('procenu', 'procjenu'),
    ('bekstv', 'bjekstv'),
    ('napredo', 'napredo'),
    ('napredn', 'napredn'),
    ('proter', 'protjer'),
    ('nasled', 'naslijed'),
    ('pogreš', 'pogriješ'),
    ('dodeli', 'dodijeli'),
    ('promen', 'promjen'),
    ('izvesn', 'izvjesn'),
    ('izvest', 'izvijest'),
    ('pobedi', 'pobijedi'),
    ('porekl', 'porijekl'),
    ('posled', 'posljed'),
    ('razume', 'razumije'),
    ('razume', 'razumje'),
    ('predst', 'predst'),
    ('odeven', 'odjeven'),
    ('dospel', 'dospjel'),
    ('pešačk', 'pješačk'),
    ('posred', 'posred'),
    ('decemb', 'decemb'),
    ('namešt', 'namješt'),
    ('zaplen', 'zaplijen'),
    ('detinj', 'djetinj'),
    ('svugde', 'svugdje'),
    ('savest', 'savjest'),
    ('proleć', 'proljeć'),
    ('nalete', 'naletje'),
    ('svetsk', 'svjetsk'),
    ('povređ', 'povrijeđ'),
    ('neuspe', 'neuspje'),
    ('vaspit', 'vaspit'),
    ('podela', 'podjela'),
    ('smatra', 'smatra'),
    ('dožive', 'doživje'),
    ('preseć', 'presjeć'),
    ('preduz', 'preduz'),
    ('stalež', 'stalež'),
    ('obelež', 'obiljež'),
    ('izgore', 'izgorje'),
    ('nedelj', 'nedjelj'),
    ('razmer', 'razmjer'),
    ('primer', 'primjer'),
    ('menjač', 'mjenjač'),
    ('svetlo', 'svjetlo'),
    ('posled', 'posljed'),
    ('zaposl', 'zaposl'),
    ('zapose', 'zaposje'),
    ('vremen', 'vremen'),
    ('neretk', 'nerijetk'),
    ('usled', 'usljed'),
    ('devet', 'devet'),
    ('želel', 'željel'),
    ('pleni', 'plijeni'),
    ('posle', 'poslije'),
    ('greši', 'griješi'),
    ('delima', 'djelima'),
    ('prene', 'prenije'),
    ('letak', 'letak'),
    ('oceni', 'ocijeni'),
    ('detet', 'djetet'),
    ('strelj','strijelj'),
    ('kolev', 'kolijev'),
    ('podne', 'podne'),
    ('koren', 'korijen'),
    ('svide', 'svidje'),
    ('čovek', 'čovjek'),
    ('cveta', 'cvjeta'),
    ('ucena', 'ucjena'),
    ('ucene', 'ucjene'),
    ('ucenu', 'ucjenu'),
    ('uceni', 'ucijeni'),
    ('decem', 'decem'),
    ('zaver', 'zavjer'),
    ('savet', 'savjet'),
    ('podel', 'podijel'),
    ('lekar', 'ljekar'),
    ('zamen', 'zamijen'),
    ('mesec', 'mjesec'),
    ('levic', 'ljevic'),
    ('levič', 'ljevič'),
    ('posed', 'posjed'),
    ('poset', 'posjet'),
    ('poseć', 'posjeć'),
    ('negde', 'negdje'),
    ('najpr', 'najprij'),
    ('smešt', 'smješt'),
    ('smest', 'smjest'),
    ('živet', 'živjet'),
    ('živel', 'živjel'),
    ('živeo', 'živio'),
    ('nedel', 'nedjel'),
    ('obe', 'obje'),
    ('odole', 'odolje'),
    ('uvide', 'uvidje'),
    ('pover', 'povjer'),
    ('dodel', 'dodjel'),
    ('svedo', 'svjedo'),
    ('never', 'nevjer'),
    ('venac', 'vijenac'),
    ('umest', 'umjest'),
    ('oseća', 'osjeća'),
    ('izmen', 'izmijen'),
    ('zamer', 'zamjer'),
    ('detalj', 'detalj'),
    ('belež', 'biljež'),
    ('osvet', 'osvjet'),
    ('obole', 'obolje'),
    ('teles', 'tjeles'),
    ('kolen', 'koljen'),
    ('uspeh', 'uspjeh'),
    ('predse', 'predsje'),
    ('izmer', 'izmjer'),
    ('izveš', 'izvješ'),
    ('izbeg', 'izbjeg'),
    ('lepot', 'ljepot'),
    ('vetar', 'vjetar'),
    ('sever', 'sjever'),
    ('nemač', 'njemač'),
    ('napad', 'napad'),
    ('izved', 'izved'),
    ('nared', 'nared'),
    ('smenj', 'smjenj'),
    ('zvezd', 'zvjezd'),
    ('delat', 'djelat'),
    ('devoj', 'djevoj'),
    ('beleg', 'biljeg'),
    ('zased', 'zasijed'),
    ('namer', 'namjer'),
    ('nemac', 'njemac'),
    ('delim', 'dijelim'),
    ('želet', 'željet'),
    ('ocenj', 'ocijenj'),
    ('greja', 'grija'),
    ('smeja', 'smija'),
    ('sreds', 'sreds'),
    ('cvet', 'cvijet'),
    ('slep', 'slijep'),
    ('deca', 'djeca'),
    ('deci', 'djeci'),
    ('decu', 'djecu'),
    ('deco', 'djeco'),
    ('sede', 'sjedje'),
    ('greh', 'grijeh'),
    ('mlek', 'mlijek'),
    ('deli', 'dijeli'),
    ('besv', 'besvj'),
    ('bled', 'blijed'),
    ('bled', 'blijed'),
    ('ubed', 'ubijed'),
    ('preć', 'prijeć'),
    ('pret', 'prijet'),
    ('smeh', 'smijeh'),
    ('sneg', 'snijeg'),
    ('svet', 'svijet'),
    ('sten', 'stijen'),
    ('odel', 'odijel'),
    ('retk', 'rijetk'),
    ('odne', 'odnije'),
    ('reši', 'riješi'),
    ('veća', 'veća'),
    ('veće', 'veće'),
    ('veći', 'veći'),
    ('zver', 'zvijer'),
    ('donel', 'donijel'),
    ('vred', 'vrijed'),
    ('iznet', 'iznijet'),
    ('delo', 'djelo'),
    ('dela', 'djela'),
    ('delo', 'djelo'),
    ('delu', 'djelu'),
    ('oseć', 'osjeć'),
    ('odeć', 'odjeć'),
    ('nemc', 'njemc'),
    ('vešt', 'vješt'),
    ('peva', 'pjeva'),
    ('venc', 'vijenc'),
    ('cent', 'cent'),
    ('ubeđ', 'ubjeđ'),
    ('nežn', 'nježn'),
    ('mesn', 'mjesn'),
    ('oset', 'osjet'),
    ('hleb', 'hljeb'),
    ('gnev', 'gnjev'),
    ('tera', 'tjera'),
    ('vide', 'vidje'),
    ('vest', 'vijest'),
    ('besn', 'bijesn'),
    ('dvem', 'dvjem'),
    ('uver', 'uvjer'),
    ('mese', 'mjese'),
    ('seti', 'sjeti'),
    ('ocen', 'ocjen'),
    ('smer', 'smjer'),
    ('pesm', 'pjesm'),
    ('ovde', 'ovdje'),
    ('mest', 'mjest'),
    ('lenj', 'lijen'),
    ('peša', 'pješa'),
    ('onde', 'ondje'),
    ('sled', 'sljed'),
    ('beža', 'bježa'),
    ('breg', 'brijeg'),
    ('lete', 'letje'),
    ('leto', 'ljeto'),
    ('letu', 'ljetu'),
    ('leti', 'ljeti'),
    ('uspe', 'uspje'),
    ('done', 'donije'),
    ('letnj', 'ljetnj'),
    ('odel', 'odjel'),
    ('smel', 'smjel'),
    ('leč', 'liječ'),
    ('rek', 'rijek'),
    ('leko', 'ljeko'),
    ('leku', 'lijeku'),
    ('leka', 'lijeka'),
    ('lev', 'lijev'),
    ('vol', 'volj'),
    ('reč', 'riječ'),
    ('cev', 'cijev'),
    ('cep', 'cijep'),
    ('pes', 'pijes'),
    ('lep', 'lijep'),
    ('une', 'unije'),
    ('bed', 'bijed'),
    ('cel', 'cijel'),
    ('ded', 'djed'),
    ('reš', 'rješ'),
    ('ver', 'vjer'),
    ('mle', 'mlje'),
    ('ređ', 'rjeđ'),
    ('več', 'vječ'),
    ('leš', 'lješ'),
    ('meš', 'mješ'),
    ('mer', 'mjer'),
    ('les', 'ljes'),
    ('pev', 'pjev'),
    ('gde', 'gdje'),
    ('sen', 'sjen'),
    ('seć', 'sjeć'),
    ('hte', 'htje'),
    ('ceni', 'cijeni'),
    ('cena', 'cijena'),
    ('cenu', 'cijenu'),
    ('cenit', 'cijeniti'),
    ('bel', 'bijel'),

 
]
def _wb(word):
    return re.compile(r'(?<![^\W\d_])' + re.escape(word) + r'(?![^\W\d_])', re.UNICODE)

def _stem(stem):
    return re.compile(r'(?<![^\W\d_])(' + re.escape(stem) + r')(\w*)', re.UNICODE | re.IGNORECASE)

_EXACT = [(_wb(e), e, i) for e, i in EXACT]
_STEMS = [(_stem(e), e, i) for e, i in STEMS]


def _apply_exact(text):
    for pat, e, i in _EXACT:
        text = pat.sub(i, text)
        text = _wb(e.capitalize()).sub(i.capitalize(), text)
        text = _wb(e.upper()).sub(i.upper(), text)
    return text

def _apply_stems(text):
    for pat, e, i in _STEMS:
        def _r(m, ije=i):
            s, suf = m.group(1), m.group(2)
            if s.isupper(): return ije.upper() + suf
            if s[0].isupper(): return ije.capitalize() + suf
            return ije + suf
        text = pat.sub(_r, text)
    return text

def replace_words(text):
    return _apply_stems(_apply_exact(text))

def process_file(inp, out):
    if not os.path.isfile(inp):
        print(f"Error: '{inp}' not found."); sys.exit(1)
    with open(inp, encoding="utf-8") as f: text = f.read()
    with open(out, "w", encoding="utf-8") as f: f.write(replace_words(text))
    print(f"Done: '{inp}' -> '{out}'")

# ─────────────────────────────────────────────────────────────────────────────
# GLAVNA ANVIL FUNKCIJA (Ovu funkciju pozivate sa klijenta)
# ─────────────────────────────────────────────────────────────────────────────
@anvil.server.callable
def ijekavizuj_tekst(ulazni_tekst):
    """Prima ekavski tekst sa UI forme, pokreće zamjene i vraća ijekavski tekst."""
    if not ulazni_tekst:
        return ""
    
    # 1. Prvo primijeni EXACT listu
    tekst = _apply_exact(ulazni_tekst)
    
    # 2. Zatim primijeni STEM listu
    konacni_tekst = _apply_stems(tekst)
    
    return konacni_tekst
